#!/usr/local/bin/python

#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ohd_child,v 1.1 2004/03/25 16:48:40 grisha Exp $

# This script is called by ohd to run external commands, sort of like
# CGI

import socket
import os
import sys

HOST = '127.0.0.1'       # The remote host
PORT = 1010              # The same port as used by the server

channel = sys.argv[1]
command = ' '.join(sys.argv[2:])

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
s.send('OUTPUT %s\r\n' % channel)

x, p = os.popen4(command)
line = p.readline()
while line:
    s.send(line)
    line = p.readline()

s.send('END OF COMMAND\n')


