#!/bin/sh

#
# Copyright 2006 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ovcleanrebuilds,v 1.1 2006/02/23 22:13:38 grisha Exp $

# This script removes the .reuild* directories left after a VPS has
# been rebuilt.

VSERVERS=/vservers/
DAYS=2

find $VSERVERS -maxdepth 1 -name ".rebuild*" -ctime +$DAYS -exec rm -rf {} \; > /dev/null 2>&1

find $VSERVERS -maxdepth 1 -name ".rebuild*" -ctime +$DAYS -exec chattr -R -i {} \;
find $VSERVERS -maxdepth 1 -name ".rebuild*" -ctime +$DAYS -exec rm -rf {} \; 


