#!/bin/sh

#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ovgenkey,v 1.1 2005/02/03 22:45:28 grisha Exp $

# regenrate the RSA key. we use a value that is known only for the
# duration of the machine's uptime for some added security


VAR_DB_OPENVPS=`python -c 'from openvps.host import cfg; print cfg.VAR_DB_OPENVPS'`

/usr/bin/python -c 'import time;print time.strftime("%Y-%M-%d-%H",(time.localtime(time.time() - float(open("/proc/uptime").read().split()[0]))))' | \
    /usr/bin/openssl genrsa -passout file:/dev/fd/0 -out $VAR_DB_OPENVPS/.key > /dev/null 2>&1

/bin/chgrp apache $VAR_DB_OPENVPS/.key
/bin/chmod 640 $VAR_DB_OPENVPS/.key



