#!/usr/bin/python

#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ping,v 1.1 2004/03/25 16:48:40 grisha Exp $

import socket
import sys
import os

HOST = '127.0.0.1'       # The remote host
PORT = 1010              # The same port as used by the server

EOF = 'END OF COMMAND'

me = os.path.split(sys.argv[0])[1]

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
s.send('%s %s\r\n' % (me, ' '.join(sys.argv[1:])))

try:
    data = s.recv(1024)
    while 1:
        if data.find(EOF) != -1:
            sys.stdout.write(data.replace(EOF, ''))
            sys.stdout.flush()
            break
        sys.stdout.write(data)
        sys.stdout.flush()
        data = s.recv(1024)
except KeyboardInterrupt:
    sys.exit()

s.close()

