#!/bin/sh
# chkconfig: 345 30 70
# description: This restores the context disk limits which should be \
#   periodically saved in /var/db/oh/disklimits by a cronjob calling ohdisk
#

#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: ovresources,v 1.2 2005/02/07 19:10:02 grisha Exp $

DISKLIMITS=`python -c 'from openvps.host import cfg; print cfg.VAR_DB_OPENVPS'`/disklimits/disklimits
PREFIX=`python -c 'from openvps.host import cfg; print cfg.PREFIX'`

# See how we were called.
case "$1" in
  start)
	echo "Generating RSA key"
	$PREFIX/ovgenkey 

	echo "Restoring context disk limits"
	/bin/sh $DISKLIMITS

	echo "Creating iptables entries for vservers"
	for devip in `python -c 'from openvps.host import vsutil; vsutil.print_vserver_ips()'`; do

	    # replace dummy with eth below because the packets from dummy0 really travel on
	    # eth0 in a DSR load-balancing scenario.

	    # "eth0:10.10.10.10" -> "-i eth0 -d 10.10.10.10"
	    DEVIP="`echo $devip | (IFS=: read A B; echo -i $A -d $B | sed -e s/dummy/eth/ )`"

	    iptables -D INPUT $DEVIP > /dev/null 2>&1
	    iptables -A INPUT $DEVIP

	    # "eth0:10.10.10.10" -> "-o eth0 -s 10.10.10.10"
	    DEVIP="`echo $devip | (IFS=: read A B; echo -o $A -s $B | sed -e s/dummy/eth/ )`"

	    iptables -D OUTPUT $DEVIP > /dev/null 2>&1
	    iptables -A OUTPUT $DEVIP
	done
	;;
  stop)
	# nothing to do here
	;;
  restart)
	$0 stop
	$0 start
	;;
  reload)
	echo Not implemented
	;;
  force-reload)
	$0 stop
	$0 start
        ;;
  status)
	echo Not implemented
	;;
  *)
	echo "Usage: ohdisklimit {start|stop|restart|reload|status}"
	exit 1
esac

exit 0




